version: '2'
services:
  app:
    build: .
    ports:
     - "8080:8080"
    links:
      - database
      - redis

  redis:
    image: "redis:alpine"

  database:
    image: postgres:9.5.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=master
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=main