version: '2'
services:
  app:
    build: .
    ports:
     - "8080:8080"
    environment:
    - process.env.APP_PORT=8080,
    - process.env.DB_HOST=database
    - process.env.DB_NAME=demo
    - process.env.CACHE_HOST=cache
    links:
      - database
      - redis

  cache:
    image: "redis:alpine"

  database:
    image: postgres:9.5.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=master
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=main